# Generated by Django 4.2.30 on 2026-09-17 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('NL_REGEX_REPLACE', 'Natural Language Regex Replace'), ('ENTITY_EXTRACTION', 'Smart Entity Extraction'), ('PII_MASKING', 'Context-Aware PII Masking')], default='NL_REGEX_REPLACE', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('s3_file_key', models.CharField(max_length=255)),
                ('natural_language_prompt', models.TextField()),
                ('generated_regex', models.TextField(blank=True, null=True)),
                ('replacement_value', models.CharField(blank=True, default='REDACTED', max_length=255, null=True)),
                ('target_columns', models.JSONField(default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('partition_count', models.IntegerField(default=0)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('output_s3_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=512)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
